### Listar todas as tarefas
GET http://localhost:5000/tarefas/listar

### Cadastrar uma nova tarefa
POST http://localhost:5000/tarefas/cadastrar
Content-Type: application/json

{
    "titulo": "Me aproximar da minha tartaruga",
    "descricao": "Me aproximar da minha tartaruga",
    "categoriaId": "b9cf9b2b-bd80-4dfc-ac74-fd8a222c68ed"
}


###Alterar uma nova tarefa
PUT http://localhost:5000/tarefas/alterar/2f1b7dc1-3b9a-4e1a-a389-7f5d2f1c8f3e


###Listar tarefas não concluidas
GET http://localhost:5000/tarefas/naoconcluidas


###Listar tarefas concluídas
GET http://localhost:5000/tarefas/concluidas